import React from "react";
import "../styles/iconsbg.css";
// import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
// import { faEnvelope } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCoffee } from "@fortawesome/free-solid-svg-icons";
function Iconsbg() {
  return (
    <div>
      {/* <p>Enjoy your coffee!</p> */}

      <section>
        <div className="row">
          <div className="icons1">
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
          </div>
          <div className="icons1">
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
          </div>
          <div className="icons1">
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
          </div>

          <div className="icons1">
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
            <FontAwesomeIcon icon={faCoffee} size="lg" />
          </div>
        </div>
      </section>
    </div>
  );
}

export default Iconsbg;
